version: "3.9"

services:

  web:
    container_name: "${DOCKER_NAME}_web"
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: "${DOCKER_NAME}_db"
    image: postgres:alpine
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d/:ro
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

#  pma:
#    container_name: "${DOCKER_NAME}_pma"
#    image: phpmyadmin/phpmyadmin
#    environment:
#      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
#      PMA_HOST: db
#      PMA_PORT: "${DB_PORT}"
#      PMA_USER: "${DB_USER}"
#      PMA_PASSWORD: "${DB_PASSWORD}"
#    ports:
#      - ${PMA_PORT}:80
#    links:
#      - db:db

volumes:
  db_data:
