version: "3.9"

services:

  db:
    container_name: "${DOCKER_NAME}_db"
    image: postgres:alpine
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  web:
    container_name: "${DOCKER_NAME}_ruby"
    build:
      context: ./docker/ruby
      dockerfile: ./ruby.dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - db
